import lab2.ex1.Book;
import lab2.ex2.*;
import java.util.Arrays;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	public static void main (String arg[]) {
//		final String[] array = {"Basic Java", "Advance Java", "Forget about Java"};
//		Book b = new Book(array);
//		System.out.println("The title of Chapter1 is " + b.getChapter(1));
//		String[] anotherArray = b.getChapters();
//		
//		System.out.println("There are " + anotherArray.length + " chapters.");
//		System.out.println(Arrays.toString(anotherArray));
//		
//		MobileComputer mc = new MobileComputer();
//		for(int i = 0; i < 10; i++)
//			mc.work();
//		
//		Charger c = new Charger();
//		MobileComputer m = new MobileComputer();
//		Phone p = new Phone();
//		c.charge(p);
//		c.charge(m);
		lab3.ex2.UIApplication.run(arg);
		
	}
    public boolean someLibraryMethod() {
        return true;
    }
}
